<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function byContact($id_client, $my_id)
    {
        $q = $this->createQueryBuilder('u')
            ->select('u')
            ->where("u.sender = :id_client AND u.receiver = :my_id")
            ->orWhere("u.sender = :my_id  AND u.receiver = :id_client")
            ->orderBy('u.id')
            ->setParameters(array('id_client'=>$id_client,'my_id'=>$my_id));

        return $q->getQuery()->getResult();
    }

    public function findAllByUser($id)
    {
        $q = $this->createQueryBuilder('u')
            ->select('u')
            ->where("u.sender = :me OR u.receiver = :me")
            ->orderBy('u.id')
            ->setParameter('me',$id);

        return $q->getQuery()->getResult();
    }
}
