security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/|(/fr/)|(/en/)
            form_login:
                provider: fos_userbundle
                use_forward:    true
                use_referer:    true
                check_path:  fos_user_security_check
                login_path:  fos_user_security_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: fos_user_profile_show
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:
               path:     fos_user_security_logout
               target: homepage
            anonymous:    true

    access_control:
        - { path: ^/\w\w/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: ROLE_USER }
        - { path: ^/\w\w/$, role: ROLE_USER }
        - { path: ^/\w\w/profile, role: ROLE_USER }
        - { path: ^/\w\w/contact, role: ROLE_USER }
        - { path: ^/\w\w/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/admin/, role: ROLE_ADMIN }